# Site settings
title: Idan Bassuk
email: idan@gmail.com
description: Expert Data Scientist
owner: Idan Bassuk
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://idanbass.github.io/" # the base hostname & protocol for your site

social:
  facebook-official: https://www.facebook.com/idan/
  
quote: If you can't explain it simply, you don't understand it well enough. 
quote-by: Albert Einstein

# Build settings
markdown: kramdown

