# Site settings
title: Idan Bassuk
owner: Idan Bassuk
email: idan.bassuk@gmail.com
whoami: Sofware Engineer Focused on A.I.
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://idanbass.github.io/" # the base hostname & protocol for your site

social-facebook: https://www.facebook.com/idan.bass.5
social-medium: https://medium.com/@Idan.Bassuk
social-linkedin: https://www.linkedin.com/in/idanbass/
social-youtube: https://www.youtube.com/playlist?list=PLOpAPAocPnu2aR8mqp6hkcUa88IKl4sXF
  
quote: If you can&#39;t explain it simply, you don&#39;t understand it well enough. 
quote-by:

# Build settings
markdown: kramdown

